//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Projeto_DA_BooKids
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalheCompra
    {
        public string Quantidade { get; set; }
        public int NrCompra { get; set; }
        public int ProdutoCodProduto { get; set; }
    
        public virtual Compra Compra { get; set; }
        public virtual Produto Produto { get; set; }
    }
}
